### ISSUE TITLE
scheduler: {sched_name} not parsing scheduler name correctly to history.txt

### ISSUE THREAD

**Issue by M4CC** [Amblyopius/AMD-Stable-Diffusion-ONNX-FP16#1] opened 2023-01-11 12:33 UTC
Hello,

I noticed that the scheduler is not being registered correctly on history.txt.

Does anyone know how to fix this?

Thank you!

**Comment by Amblyopius** [comment] 2023-01-11 13:17
I noticed you've got an open PR on OnnxDiffusersUI with no response. This question also belongs there. If the UI is no longer maintained, I'll fork it and we can take it from there.

The issue seemed to be caused by following line not really doing what it should do:
    sched_name = str(pipe.scheduler._class_name)

There are other generic issues with schedulers not always doing what they should (e.g. EulerA does not seem to work as expected, haven't tried yet to figure out what breaks in combination with ONNX)

**Comment by M4CC** [comment] 2023-01-12 15:20
Thank you very much for following up on this!

**Comment by Amblyopius** [comment] 2023-01-23 01:03
Has been fixed in OnnxDiffusersUI along with other improvements.

**Closed by Amblyopius** 2023-01-23 01:03 UTC
